name: anton_test_dbt
version: "1.0.0"
config-version: 2
profile: anton_test_dbt

seed-paths: ["seeds"]
macro-paths: ["macros"]
model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
snapshot-paths: ["snapshots"]

target-path: target
clean-targets:
  - target
  - dbt_packages
  - logs

# schema comes from profiles.yml → env var DBT_SCHEMA
# do NOT set +schema here unless you also override generate_schema_name
# (default dbt would otherwise create target_schema_<custom>)
